name: TopLogin
main: cn.guestc.nukkit.login.TopLogin
version: "1.0.0"
api: ["1.0.5"]
load: POSTWORLD
author: Guestc
description: "a simple Login for NukkitX"


commands:
  login:
    description: "login Command"
    usage: "/login [Passwd]"
    permission: toplogin.cmd.login
  passwd:
    description: "change passwd command"
    usage: "/passwd [new passwd]"
    permission: toplogin.cmd.passwd
  setpasswd:
    description: "change the user passwd"
    usage: "/setpasswd [user] [new passwd]"
    permission: toplogin.cmd.setpasswd
  setmail:
    description: "change mail command"
    usage: "/setmail [mail]"
    permission: toplogin.cmd.setmail

permissions:
  toplogin.cmd.login:
    description: "allows the user login in server"
    default: true
  toplogin.cmd.passwd:
    description: "allows the user change passwd in server"
    default: true
  toplogin.cmd.setpasswd:
    description: "allows the Op set user's passwd in server"
    default: op
  toplogin.cmd.setmail:
    description: "allows the user change mail in server"
    default: true